### PR TITLE
fix windows support

### LINKED ISSUE #42: Tests cannot be found on windows, due to usage of `\` instead of `/` in the file path.
Have 👋, thank you for this nice plugin!

I use **Windows** and **Neovim 0.8**, and I would love to use this plugin with it.

When I try to run my tests through `require('neotest').run.run()`, then the test cannot be found. The output is as follows:
```bash
> jest {...} C:\{...}\component.spec.ts

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\{...}\frontend
  38 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 8 matches
  testPathIgnorePatterns: \\node_modules\\ - 38 matches
  testRegex:  - 0 matches
Pattern: C:\{...}\component.spec.ts - 0 matches
```

When I manually run the test in the terminal, then the result is the same. But when I change the `\`s in the command to `/`s, then the tests can be found and they succeed:
```bash
> jest {...} C:/{...}/component.spec.ts

Determining test suites to run...
ngcc-jest-processor: running ngcc
 PASS  src/component.spec.ts
```

It would be nice to fix this. How can I make this work?

Thank you for your support :)

### PR DESCRIPTION
**Pull request by Pineappletooth**
This plugin in windows has 2 issues:

1) Jest only accepts paths with forward slash but the plugin sends it backwards as reported in #42

~~2) After solving the first issue i noticed that neotest doesn't update the sign for each test making every test appear with an X even if the test passed. This is caused due to the test having an id like `c:\\path\file::test_name` and the Jest output reports the path like `C:\\path\file::test_name` (notice the capital drive)~~  It seems that neotest now respects the case of the test id so this is no longer an issue.

This PR attemps to solve both issues.

First issue was solved using ` vim.fs.normalize` as recommended in https://github.com/nvim-neotest/neotest-jest/pull/44#issuecomment-1420417168.

~~Second issue was solved adding a windows only validation that changes the case of the drive.~~

Tested in windows everything works as expected. Should not cause any issue in other platforms.

Fixes #42 
Supersedes #44

### CODE REVIEW

**Review by haydenmeade — APPROVED** [review]
LGTM, fix merge conflict then tag me and I'll merge it

**Comment by Pineappletooth** [comment]
@haydenmeade done, thanks.

**Comment by bad4iz** [comment]
this is very relevant and necessary. How are things progressing on this issue?

**Comment by bad4iz** [comment]
in my opinion, the second point does not work
image

image

**Comment by Pineappletooth** [comment]
@bad4iz Thanks for the report, i updated my dependencies and it seems that the second point was fixed in another place (probably in the neotest repo) and now the original test id respects the drive case, so the windows specific hack is no longer needed.

I removed it and everything seems to be working as expected again.
Could you try and confirm please?

**Comment by bad4iz** [comment]
yes it works 
image

**Comment by bad4iz** [comment]
@haydenmeade this is very relevant and necessary. How are things progressing on this issue?

**Pull request merged**
