### PR TITLE
Remove ' from testNamePatterns to fix failing tests

### LINKED ISSUE #68: The extra `'` in `testNamePattern` causes my tests to be ignored
https://github.com/nvim-neotest/neotest-jest/blob/e60280f53ef9f84fd827aecae1e2f732ba4326b1/lua/neotest-jest/init.lua#L359-L365

I have set a custom `jestCommand` in my adapter  configuration, something specific to my project like `yarn run custom-script ...`. Now when I one single test, the test name pattern in the output is not correct, it has extra `'` like this : 

```
 '--testNamePattern='\''^Class someMethod should return something$'\'
```

If I directly run this command in the shell, no test is matching. But if I remove the extra `'`, it runs as expected. 

```
'--testNamePattern=^Class someMethod should return something$'
```

I have locally updated the plugin as so and it works fine now: 

```
local testNamePattern = ".*"

  if pos.type == "test" or pos.type == "namespace" then
    -- pos.id in form "path/to/file::Describe text::test text"
    local testName = string.sub(pos.id, string.find(pos.id, "::") + 2)
    testName, _ = string.gsub(testName, "::", " ")
    testNamePattern = "^" .. escapeTestPattern(testName)
    if pos.type == "test" then
      testNamePattern = testNamePattern .. "$"
    else
      testNamePattern = testNamePattern .. "'"
    end
  end
```

Do you think it could break things if the `'` is completely removed?

### PR DESCRIPTION
**Pull request by JaapBarnhoorn**
fixes #68 

The suggestion done in #68 fixes my problem with Jest not finding the tests.
I'm not sure if this is a valid fix, but this works for me on Linux

### CODE REVIEW

**Comment by mikaoelitiana** [comment]
@haydenmeade do you think this solution could break something we are not aware of ?

**Comment by mikaoelitiana** [comment]
@JaapBarnhoorn could you please rebase your change with latest `main` to fix the conflict?

**Comment by haydenmeade** [comment]
> @haydenmeade do you think this solution could break something we are not aware of ?

Seems ok if it's been tested

**Comment by mikaoelitiana** [comment]
> > @haydenmeade do you think this solution could break something we are not aware of ?
> 
> Seems ok if it's been tested

I have tested it for a while and did not encounter any issue so far

**Pull request closed without merging**
